ServerEvents.recipes(event => {
	event.remove({ id: 'create:crushing/crimsite_recycling' })
	event.remove({ id: 'create:crushing/asurine_recycling' })
	event.remove({ id: 'createdieselgenerators:compacting/plant_oil'})
	event.remove({ id: 'createmr:crushing/lapis_from_diamond'})
	event.remove({ id: 'create:crushing/diamond/scrap_diamond'})
	event.remove({ id: 'createmr:crushing/emerald_from_scorchia'})
	event.remove({ id: 'create_dd:crushing/scorchia_recycling'})
	event.remove({ id: 'create_dd:crushing/scorchia'})
	event.remove({ id: 'createdeco:pressing/andesite_sheet'})
	event.remove({ id: 'create_things_and_misc:crushed_magma_crush'})
	event.remove({ id: 'create:crushing/misc/scrap_magma_block'})
	event.remove({ id: 'create_dd:crafting/diamond_shard_compacting'})
	event.remove({ id: 'create_dd:crafting/diamond_shard_from_decompacting'})
})